#!/bin/bash
# Script to allow MQTT broker through macOS firewall

echo "=== MQTT Firewall Fix for macOS ==="
echo ""
echo "This script will help you allow MQTT (port 1883) through macOS firewall."
echo ""
echo "Option 1: Allow via System Settings (Recommended)"
echo "  1. Open System Settings > Network > Firewall"
echo "  2. Click 'Options...' or 'Firewall Options'"
echo "  3. Click '+' to add an application"
echo "  4. Navigate to /usr/local/sbin/mosquitto"
echo "  5. Set it to 'Allow incoming connections'"
echo ""
echo "Option 2: Allow via Terminal (requires sudo)"
echo "  Run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/local/sbin/mosquitto"
echo "  Then: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /usr/local/sbin/mosquitto"
echo ""
echo "Option 3: Temporarily disable firewall (NOT recommended for production)"
echo "  System Settings > Network > Firewall > Turn Off Firewall"
echo ""
echo "=== Current Firewall Status ==="
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate 2>/dev/null || echo "Cannot check firewall status (requires sudo)"
echo ""
echo "=== Testing Connection ==="
echo "From another device on your network, test with:"
echo "  telnet 10.56.196.91 1883"
echo "  or"
echo "  nc -zv 10.56.196.91 1883"

